### ISSUE TITLE
Beware race conditions

### ISSUE THREAD

**Issue by pakal** [joshburnett/multitimer#2]
There are setters to access and modify args/kwargs, and the doc shows how to modify mutable input arguments, but it seems dangerous since this multithreaded code is not protected by lock, and so subject to weird race conditions if the main thread modifies variables during a new run of the thread task.
Maybe this danger should be noted in docs, or locks should be added to ensure these operations are atomic?

**Comment by joshburnett** [comment]
You are correct, this is an issue.  Thanks for pointing it out!  I haven't run into it myself, but that's just because I don't tend to use the capabilities of modifying the input arguments after the timer has been set up.

I agree, it would be nice to have some locks put in place as you suggested.  Not quite sure when I'll have time to get to this, unfortunately.  Pull requests are welcome!

I'll see if I can at least put a brief note in the docs to make sure people know that the issue is lurking.

**Comment by pakal** [comment]
I think a warning in docs would suffice, modifying params at runtime, especially modifying mutable arguments, are imho corner cases (and not entirely fixable against race conditions).
